[openai]
truth_query_assistant_id = "asst_..."
perspective_assistant_id = "asst_..."
combined_assistant_id = "asst_..."
narrative_identification_assistant_id = "asst_..."
link_assistant_id = "asst_..."
api_key = "sk-proj-..."
hashtag_assistant_id = "..."
[exa]
api_key = "..."

[google]
sheet_id = "..."
type = "service_account"
project_id = "..."
private_key_id = "..."
private_key = "-----BEGIN PRIVATE KEY-----\...\n-----END PRIVATE KEY-----\n"
client_email = "....iam.gserviceaccount.com"
client_id = "..."
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/....iam.gserviceaccount.com"
universe_domain = "googleapis.com"